### ISSUE TITLE
Breaks with AWS SDK v3.0

### ISSUE THREAD

**Issue by eternalinteractive** [fedemotta/yii2-aws-sdk#1]
AWS version 3.0 was announced on 5/27/15: http://blogs.aws.amazon.com/php/post/Tx29HZZVCASVU21/Version-3-of-the-AWS-SDK-for-PHP

Since you don't specify which version to use, 'Aws\Common\Aws'  class reference doesn't work. Please refer to http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html for migration information.

As a temporary fix, one can add the following to their main composer.json file.
"aws/aws-sdk-php": "2.*"

**Comment by fedemotta** [comment]
Thanks @canreo. I was not aware of this release.

For now this extension will only work with the SDK version 2.0. I will update the extension to work with version 3.0 ASAP.

Closed with f24782963d60741ba6e511337ed72bab86d80128

**Comment by fedemotta** [comment]
The extension was updated to work with AWS version 3 in the release 2.0
