### ISSUE TITLE
Setting unknown property: fedemotta\awssdk\AwsSdk::key

### ISSUE THREAD

**Issue by gotaholen1** [fedemotta/yii2-aws-sdk#3]
Been using this for a while, and now I am getting this...

Setting unknown property: fedemotta\awssdk\AwsSdk::key

**Comment by gotaholen1** [comment]
It seems that there is some configuration issue with the way credentials are being stored with the newer version.  I was able to revert to the old AWS version and get it working.

**Comment by fedemotta** [comment]
Which version is working now?

**Comment by asmythe** [comment]
I am having the same problem ... what do I need to change to get it to work? Any help would be appreciated.

**Comment by asmythe** [comment]
I changed the config to

```
        'awssdk' => [
            'class' => 'fedemotta\awssdk\AwsSdk',
            'key' => 'my-key',
            'secret' => 'my-secret',
            'region' => 'us-east-1', //i.e.: 'us-east-1'
//            'version' => 'latest', //i.e.: 'latest'
        ],

```

that got past the first problem. But now I get 'Call to undefined method Aws\Common\Aws::createS3()'

Maybe something is wrong with this distribution? It doesn't seem to include the actual AWS SDK

**Comment by fedemotta** [comment]
You should update your composer to get AWS version 3.x. That undefined method is version 2.x. The configuration should be like this:

``` php
'awssdk' => [
            'class' => 'fedemotta\awssdk\AwsSdk',
            'credentials' => [
                'key' => 'AKKDKKDEWEQWE',
                'secret' => '4kdljflkajklsfjlaksfjlksjflksajlfaj',
            ],
            'region' => 'us-east-1', //i.e.: 'us-east-1'
            'version' => 'latest', //i.e.: 'latest'
        ],
```
