### ISSUE TITLE
How to change Yii2 assets directory to AWS S3

### ISSUE THREAD

**Issue by nagaokashi** [fedemotta/yii2-aws-sdk#6]
This is my current assets setting.

```
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
    //...
```
I also have an account on AWS S3. I could upload/download files to S3 successful by using this extension. Because I'm using heroku.com to run my website, all assets files will be removed when heroku's dynno is stopped restart. So I want to change assets directory to other server like S3.

How to change yii2 assets directory to AWS S3 ?

Thanks!

**Comment by mastershaig** [comment]
Same problem

**Comment by fedemotta** [comment]
@nagaokashi @mastershaig 
I think this is more a Yii question. You can provide a CDN server like this:
```php
class CdnAsset extends AssetBundle
{
    public $css = [
        '//fonts.googleapis.com/css?family=Roboto:300,400,500,700',
        '//fonts.googleapis.com/icon?family=Material+Icons',
    ];
}
```
