### ISSUE TITLE
How to pass extra arguments like fileDownload to get_object 

### ISSUE THREAD

**Issue by Er-Kalpesh** [fedemotta/yii2-aws-sdk#7]
Look here : http://docs.aws.amazon.com/AWSSDKforPHP/latest/index.html#m=AmazonS3/get_object

I want to use code like : 
$s3 = new AmazonS3();
$bucket = 'my-bucket' . strtolower($s3->key);
 
$response = $s3->get_object($bucket, 'large_video.mov', array(
    'fileDownload' => 'large_video.mov'
));
 
// Success?
var_dump($response->isOK());

**So how can i pass "fileDownload" params in your sdk ?**

**Comment by fedemotta** [comment]
@Er-Kalpesh Let me know if this work, you should already resolved:
```
Yii::$app->awssdk->region = 'sa-east-1';
$aws = Yii::$app->awssdk->getAwsSdk();
//use s3
$s3 = $aws->createS3();
$bucket = 'my-bucket' . strtolower($s3->key);
$response = $s3->get_object($bucket, 'large_video.mov', array('fileDownload' => 'large_video.mov'));
```
It should be working like this.

**Comment by Er-Kalpesh** [comment]
Thanks for your response @fedemotta but its very older request so I can not test it.

**Comment by fedemotta** [comment]
I know! Sorry about that.
